version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: